name: Safe Mom
run-name: ${{ github.actor }} is making changes 🚀.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up Docker
      run: docker --version

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t sebbiemzing/safe-mom-web:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push sebbiemzing/safe-mom-web:latest
