name: Safe Mom
run-name: ${{ github.actor }} is making changes 🚀.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and Test Docker Container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up docker
      run: docker --version

    - name: Build docker image
      run: docker build -t safemom-app .
    
    - name: Build docker container
      run: |
            docker run -d --name safemom-container -p 5000:5000 \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              safemom-app

    deploy:
      name: Deploy to Render
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/master'

      steps:
        - name: Trigger Render Deployment
          run: |
            curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
